spring:
  jackson:
    deserialization:
      fail-on-unknown-properties : true

  datasource:
    url: jdbc:postgresql://10.0.0.204:5432/postgres
    username: postgres
    password: 930324

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    show-sql: true

logging:
    level:
        org:
          hibernate.type.descriptor.sql: trace
          springframwork.security: DEBUG

my-app:
  admin-password: admin
  admin-username: admin@email.com
  user-username: user@email.com
  user-password: user
  client-id: myApp
  client-secret: pass